[package]
name = "kv_store"
version = "0.1.0"
edition = "2021"

[dependencies]
edfsm = { path = "../event-driven", version = "0.7" }
derive_more = { version = "1", features = ["from"] }

[dev-dependencies]
streambed-patterns = "0.11"
tokio = { version = "1", features = ["full"] }
edfsm-fixtures = { path = "../edfsm-fixtures", version = "0.1" }
machine = { path = "../machine", version = "0.1" }
