[package]
name = "kv_store"
description = "A KV Store based on edfsm FSM"
readme = "README.md"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
edfsm.workspace = true
derive_more = { version = "1", features = ["from"] }

[dev-dependencies]
machine.workspace = true
streambed-patterns = "0.11"
tokio = { version = "1", features = ["full"] }
serde = "1"
